export const skills = {
    heading: "Skills",
    quote: "Build your skills, not your resume",
    techSkills: [
        "JavaScript",
        "ReactJS",
        "Flutter",
        "Redux",
        "C++",
        "C#",
        "C",
        "Java",
        "Python",
        "Dart",
        "HTML",
        "CSS",
        "jQuery",
        "Bootstrap",
        "Material Design",
        "Git",
        "GitHub",
    ],
    industryKnowledge: [
        "Marketing",
        "Publicity",
        "Content Writing",
        "Creative Writing",
        "Web Content",
        "Frontend",
        "Web Development",
        "Android",
    ],
    interpersonalSkills: [
        "Communication",
        "Teaching",
        "Time Management",
        "Leadership",
        "Management",
        "Human Resouce Management",
    ]
};